name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package

      # Deploy your application
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_963bd868-f7b4-4258-8032-dca87fd5343d
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
